### ISSUE TITLE
TOSCA-Studio Linux Release Executable Configuration

### ISSUE THREAD

**Issue by jerbel** [occiware/TOSCA-Studio#5]
### Description
When downloading a release of TOSCA-Studio for Linux the TOSCA-Studio file is not executable which has to be adjusted manually.

**Comment by stephaniechallita** [comment]
Hello @jerbel 

I've just retrieved the release on a laptop running Linux, unzipped it and checked privileges and it appears that `TOSCA-Studio` is executable:

![screen-x-release](https://user-images.githubusercontent.com/19570549/68088106-ffe22300-fe5b-11e9-8ba8-0c58a65d4c09.png)

Would you mind double-check the privilege? Or maybe I misunderstand what is the problem.

Thank you.

**Comment by jerbel** [comment]
I just downloaded the latest TOSCA-Studio release and it was executable. Everything works fine now and I do not experience the issue any more.
